language: node_js
node_js:
- '8'
- '10'
script:
- npm run build
cache: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
